# This is a basic workflow to help you get started with Actions
name: update-release-assets
# Controls when the action will run.
on:
  release:
    types:
      - created
  workflow_dispatch:

env:
  JAR_NAME: kinkao-0.0.1-SNAPSHOT.jar

jobs:
  release:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          name: kinkao-${{ matrix.os }}

      - name: Rename file
        run: |
          mv kinkao-${{ matrix.os }}/${{ env.JAR_NAME }} kinkao-${{ matrix.os }}.jar

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "*.jar"

